# -*- coding: utf-8 -*-
"""Report models for GuardPro."""

from . import incident_report_pdf
from . import shift_report_pdf
from . import tour_log_report_pdf
from . import attendance_report_pdf
from . import daily_activity_report_pdf
from . import guard_id_card_pdf
from . import visitor_management_report_pdf
from . import package_management_report_pdf
from . import lost_found_report_pdf
from . import key_management_report_pdf
from . import compliance_audit_report_pdf
from . import sla_management_report_pdf
from . import guard_performance_report_pdf
from . import guard_credential_report_pdf
from . import guard_task_report_pdf
from . import resident_complaint_report_pdf
from . import equipment_report_pdf
from . import guard_background_check_report_pdf
from . import guard_drug_test_report_pdf
from . import guard_vaccination_report_pdf
from . import client_feedback_report_pdf
from . import emergency_broadcast_report_pdf
from . import emergency_procedure_report_pdf
from . import shift_swap_request_report_pdf
from . import security_tour_route_report_pdf
# Phase 2 PDF Reports (Nov 2025) - All 11 new reports
from . import incident_investigation_report_pdf
from . import training_certificate_pdf
from . import geofence_alert_report_pdf
from . import shift_swap_approval_form_pdf
from . import guard_attendance_summary_pdf
from . import site_security_summary_pdf
from . import checkpoint_scan_compliance_pdf
from . import monthly_performance_dashboard_pdf
from . import emergency_drill_report_pdf
from . import sla_performance_report_pdf
from . import equipment_maintenance_history_pdf
from . import credential_compliance_summary_pdf
from . import visitor_access_log_pdf
from . import lost_found_inventory_pdf
from . import package_delivery_summary_pdf
