version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: esign-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - default
      - web-proxy-net

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_AZURE_CLIENT_ID=${NEXT_PUBLIC_AZURE_CLIENT_ID}
        - NEXT_PUBLIC_AZURE_TENANT_ID=${NEXT_PUBLIC_AZURE_TENANT_ID}
        - NEXT_PUBLIC_API_URL=https://esign.berkeleyuae.com/api
    container_name: esign-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://esign.berkeleyuae.com/api
      - NEXT_PUBLIC_AZURE_CLIENT_ID=${NEXT_PUBLIC_AZURE_CLIENT_ID}
      - NEXT_PUBLIC_AZURE_TENANT_ID=${NEXT_PUBLIC_AZURE_TENANT_ID}
    depends_on:
      - backend
    restart: always
    networks:
      - default
      - web-proxy-net

  db:
    image: postgres:15-alpine
    container_name: esign-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esign_metadata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:


networks:
  default:
  web-proxy-net:
    external: true
