# -*- coding: utf-8 -*-
from . import res_company
from . import hr_employee
from . import hr_work_location
from . import attendance_job_code
from . import hr_attendance
from . import attendance_policy_rule
from . import attendance_public_holiday
from . import attendance_report_preset
from . import attendance_scheduled_export
from . import attendance_roster
from . import attendance_location_log
from . import attendance_metrics_snapshot
from . import attendance_daily_mobility
from . import attendance_biometric_device
from . import attendance_biometric_event
from . import attendance_geofence_alert
from . import attendance_odoo_sync
from . import ir_websocket
from . import res_config_settings
