# -*- coding: utf-8 -*-
{
    'name': 'Berkeley Workforce',
    'version': '18.0.3.2.10',
    'category': 'Human Resources/Attendance',
    'summary': 'Berkeley Workforce — attendance, biometrics, ZKTeco iClock, policies, rosters, maps, exports',
    'depends': [
        'hr',
        'hr_holidays',
        'hr_attendance',
        'hr_fleet',
        'fleet',
        'mail',
        'resource',
        'web',
        'base_setup',
        'portal',
    ],
    'data': [
        'security/attendance_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_cron_scheduled_export.xml',
        'data/ir_cron_bw_extended.xml',
        'data/ir_actions_server_data.xml',
        'views/hr_work_location_views.xml',
        'views/hr_attendance_views.xml',
        'views/hr_employee_views.xml',
        'views/attendance_biometric_views.xml',
        'views/attendance_geofence_alert_views.xml',
        'views/attendance_report_views.xml',
        'views/attendance_features_views.xml',
        'views/attendance_analytics_views.xml',
        'views/res_company_views.xml',
        'views/attendance_integration_views.xml',
        'views/res_config_settings_views.xml',
        'views/portal_workforce_templates.xml',
        'views/menus.xml',
        'data/ir_cron_odoo_sync_outbox.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'attendance_core/static/src/map/attendance_map_action.js',
            'attendance_core/static/src/dashboard/bw_live_hr_dashboard.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
