{
    "name": "Sales Bid Board",
    "version": "18.0.2.0.1",
    "summary": "Bid/No-Bid pipeline and decision management",
    "category": "Sales",
    "author": "Berkeley UAE",
    "license": "LGPL-3",
    "depends": [
        "sale_management",
        "crm",
        "crm_iap_enrich",
        "contacts",
        "mail",
        "web",
        "auth_oauth",
        "spreadsheet_dashboard",
    ],
    "data": [
        "data/microsoft_oauth.xml",
        "security/bid_security.xml",
        "security/bid_rules.xml",
        "security/bid_crm_lead_rules.xml",
        "security/ir.model.access.csv",
        "security/bid_decline_review_wizard_access.xml",
        "data/bid_project_stage_data.xml",
        "data/bid_governance_cron_data.xml",
        "data/bid_email_cron_record_rule.xml",
        "data/bid_config_parameter_data.xml",
        "data/bid_proposal_sequence.xml",
        "data/bid_crm_fm_tags.xml",
        "data/bid_crm_server_actions.xml",
        "views/bid_training_documentation_views.xml",
        "views/bid_project_views.xml",
        "views/bid_calendar_views.xml",
        "views/bid_proposal_views.xml",
        "views/bid_crm_lead_views.xml",
        "views/bid_submission_views.xml",
        "views/bid_team_member_views.xml",
        "views/bid_notification_views.xml",
        "views/bid_settings_views.xml",
        "views/sales_bid_board_dashboard_views.xml",
        "views/sales_bid_board_unified_analytics_views.xml",
        "data/sales_bid_board_dashboard_data.xml",
        "reports/bid_project_report.xml",
        "reports/sales_bid_board_dashboard_report.xml",
        "views/bid_board_menu.xml",
        "views/bid_restrict_global_apps_dashboards.xml",
        "views/bid_contacts_sidebar_label.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "sales_bid_board/static/src/css/bid_board_training_doc.scss",
            "sales_bid_board/static/src/xml/bid_board_training_action.xml",
            "sales_bid_board/static/src/xml/sales_bid_board_unified_analytics_templates.xml",
            "sales_bid_board/static/src/js/bid_board_training_action.js",
            "sales_bid_board/static/src/js/sales_bid_board_dashboard.js",
            "sales_bid_board/static/src/js/sales_bid_board_salesperson_dashboard.js",
            "sales_bid_board/static/src/js/sales_bid_board_unified_analytics.js",
            "sales_bid_board/static/src/xml/sales_bid_board_dashboard_templates.xml",
        ],
        "web.assets_qweb": [
            "sales_bid_board/static/src/xml/sales_bid_board_dashboard_templates.xml",
            "sales_bid_board/static/src/xml/sales_bid_board_unified_analytics_templates.xml",
        ],
    },
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
}
