{
    "name": "Sales Bid Board",
    "version": "18.0.1.0.34",
    "summary": "Bid/No-Bid pipeline and decision management",
    "category": "Sales",
    "author": "Berkeley UAE",
    "license": "LGPL-3",
    "depends": ["sale_management", "mail", "web", "auth_oauth"],
    "data": [
        "data/microsoft_oauth.xml",
        "security/bid_security.xml",
        "security/bid_rules.xml",
        "security/ir.model.access.csv",
        "data/bid_project_stage_data.xml",
        "data/bid_governance_cron_data.xml",
        "data/bid_email_cron_record_rule.xml",
        "data/bid_config_parameter_data.xml",
        "views/bid_training_documentation_views.xml",
        "views/bid_project_views.xml",
        "views/bid_submission_views.xml",
        "views/bid_team_member_views.xml",
        "views/bid_notification_views.xml",
        "views/bid_settings_views.xml",
        "views/sales_bid_board_dashboard_views.xml",
        "views/sales_bid_board_salesperson_dashboard_views.xml",
        "data/sales_bid_board_dashboard_data.xml",
        "reports/sales_bid_board_dashboard_report.xml",
        "views/bid_board_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "sales_bid_board/static/src/css/bid_board_training_doc.scss",
            "sales_bid_board/static/src/xml/bid_board_training_action.xml",
            "sales_bid_board/static/src/js/bid_board_training_action.js",
        ],
        "web.assets_web": [
            "sales_bid_board/static/src/js/sales_bid_board_dashboard.js",
            "sales_bid_board/static/src/js/sales_bid_board_salesperson_dashboard.js",
            "sales_bid_board/static/src/xml/sales_bid_board_dashboard_templates.xml",
        ],
        "web.assets_backend_lazy": [
            "sales_bid_board/static/src/js/sales_bid_board_dashboard.js",
            "sales_bid_board/static/src/js/sales_bid_board_salesperson_dashboard.js",
        ],
        "web.assets_qweb": [
            "sales_bid_board/static/src/xml/sales_bid_board_dashboard_templates.xml",
        ],
    },
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
}
